AWSTemplateFormatVersion: 2010-09-09
Description: >-
  VPC: public subnets in two availability zones
  template
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: VPC Parameters
        Parameters:
          - ClassB
  'AWS::CloudFormation::Designer':
    b3fdfb1a-746b-4b34-a3b3-f870c2e14ec4:
      size:
        width: 60
        height: 60
      position:
        x: 360
        'y': 320
      z: 1
      embeds: []
    4e30e35b-1c1e-4cb0-a8ff-20d533cf312f:
      size:
        width: 740
        height: 270
      position:
        x: -430
        'y': 220
      z: 1
      embeds:
        - b3197718-8841-4ec6-a706-aba00c381d3c
        - a685b490-29e9-46c1-af3a-7aad39dfa69c
        - 8df0b839-558a-4f5a-bd70-3e2a6d9acdc9
        - 397cd4fa-c05c-425f-a020-4f12ad5aca59
        - 5fe95414-30b3-4964-8d53-c5d900ab1288
    b3197718-8841-4ec6-a706-aba00c381d3c:
      size:
        width: 310
        height: 160
      position:
        x: -410
        'y': 310
      z: 2
      parent: 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
      embeds:
        - 42272aee-c9ae-4f9c-bd77-355e46285777
        - f63a9655-85ce-4ad4-b5ea-56183b01cc7b
      iscontainedinside:
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
    42272aee-c9ae-4f9c-bd77-355e46285777:
      size:
        width: 60
        height: 60
      position:
        x: -380
        'y': 370
      z: 3
      parent: b3197718-8841-4ec6-a706-aba00c381d3c
      embeds: []
      iscontainedinside:
        - b3197718-8841-4ec6-a706-aba00c381d3c
        - b3197718-8841-4ec6-a706-aba00c381d3c
        - b3197718-8841-4ec6-a706-aba00c381d3c
    f63a9655-85ce-4ad4-b5ea-56183b01cc7b:
      size:
        width: 60
        height: 60
      position:
        x: -260
        'y': 370
      z: 3
      parent: b3197718-8841-4ec6-a706-aba00c381d3c
      embeds: []
      iscontainedinside:
        - b3197718-8841-4ec6-a706-aba00c381d3c
        - b3197718-8841-4ec6-a706-aba00c381d3c
        - b3197718-8841-4ec6-a706-aba00c381d3c
    a685b490-29e9-46c1-af3a-7aad39dfa69c:
      size:
        width: 140
        height: 80
      position:
        x: -70
        'y': 400
      z: 2
      parent: 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
      embeds: []
      iscontainedinside:
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
    8df0b839-558a-4f5a-bd70-3e2a6d9acdc9:
      size:
        width: 140
        height: 80
      position:
        x: -70
        'y': 280
      z: 2
      parent: 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
      embeds: []
      iscontainedinside:
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
    397cd4fa-c05c-425f-a020-4f12ad5aca59:
      size:
        width: 150
        height: 80
      position:
        x: 140
        'y': 400
      z: 2
      parent: 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
      embeds: []
      iscontainedinside:
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
    b698254e-99c1-457a-8fc5-0c5ca09941b3:
      source:
        id: b3197718-8841-4ec6-a706-aba00c381d3c
      target:
        id: 397cd4fa-c05c-425f-a020-4f12ad5aca59
      z: 2
    c2ddb713-b6b3-4361-9668-1b9c4497fb5d:
      source:
        id: a685b490-29e9-46c1-af3a-7aad39dfa69c
      target:
        id: 397cd4fa-c05c-425f-a020-4f12ad5aca59
      z: 2
    5fe95414-30b3-4964-8d53-c5d900ab1288:
      size:
        width: 140
        height: 80
      position:
        x: 140
        'y': 280
      z: 2
      parent: 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
      embeds: []
      iscontainedinside:
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
        - 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
    59502b0c-b755-4fe8-9cfd-50b75f0c08f8:
      source:
        id: b3197718-8841-4ec6-a706-aba00c381d3c
      target:
        id: 5fe95414-30b3-4964-8d53-c5d900ab1288
      z: 2
    008e464e-4675-438b-89a9-038eeebaf8e7:
      source:
        id: 8df0b839-558a-4f5a-bd70-3e2a6d9acdc9
      target:
        id: 5fe95414-30b3-4964-8d53-c5d900ab1288
      z: 2
    2e142bcb-4541-436a-9fe8-29ea4747fc70:
      source:
        id: 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
      target:
        id: b3fdfb1a-746b-4b34-a3b3-f870c2e14ec4
      z: 1
Parameters:
  ClassB:
    Description: Class B of VPC (10.XXX.0.0/16)
    Type: Number
    Default: 0
    ConstraintDescription: 'Must be in the range [0-255]'
    MinValue: 0
    MaxValue: 255
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Sub '10.${ClassB}.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub '10.${ClassB}.0.0/16'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4e30e35b-1c1e-4cb0-a8ff-20d533cf312f
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '10.${ClassB}.0.0/16'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b3fdfb1a-746b-4b34-a3b3-f870c2e14ec4
  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2e142bcb-4541-436a-9fe8-29ea4747fc70
  SubnetAPublic:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs ''
      CidrBlock: !Sub '10.${ClassB}.0.0/20'
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: A public
        - Key: Reach
          Value: public
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5fe95414-30b3-4964-8d53-c5d900ab1288
  SubnetBPublic:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !GetAZs ''
      CidrBlock: !Sub '10.${ClassB}.32.0/20'
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: B public
        - Key: Reach
          Value: public
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 397cd4fa-c05c-425f-a020-4f12ad5aca59
  RouteTablePublic:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: A Public
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8df0b839-558a-4f5a-bd70-3e2a6d9acdc9
  RouteTableBPublic:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: B Public
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a685b490-29e9-46c1-af3a-7aad39dfa69c
  RouteTableAssociationAPublic:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SubnetAPublic
      RouteTableId: !Ref RouteTablePublic
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 008e464e-4675-438b-89a9-038eeebaf8e7
  RouteTableAssociationBPublic:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SubnetBPublic
      RouteTableId: !Ref RouteTableBPublic
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c2ddb713-b6b3-4361-9668-1b9c4497fb5d
  NetworkAclPublic:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Public
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b3197718-8841-4ec6-a706-aba00c381d3c
  SubnetNetworkAclAssociationAPublic:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      SubnetId: !Ref SubnetAPublic
      NetworkAclId: !Ref NetworkAclPublic
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 59502b0c-b755-4fe8-9cfd-50b75f0c08f8
  SubnetNetworkAclAssociationBPublic:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      SubnetId: !Ref SubnetBPublic
      NetworkAclId: !Ref NetworkAclPublic
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b698254e-99c1-457a-8fc5-0c5ca09941b3
  NetworkAclEntryInPublicAllowAll:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref NetworkAclPublic
      RuleNumber: 99
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f63a9655-85ce-4ad4-b5ea-56183b01cc7b
  NetworkAclEntryOutPublicAllowAll:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref NetworkAclPublic
      RuleNumber: 99
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 42272aee-c9ae-4f9c-bd77-355e46285777
Outputs:
  TemplateID:
    Description: cloudonaut.io template id.
    Value: vpc/vpc-2azs
  TemplateVersion:
    Description: cloudonaut.io template version.
    Value: 9.0.0
  StackName:
    Description: Stack name.
    Value: !Sub '${AWS::StackName}'
  AZs:
    Description: AZs
    Value: 2
    Export:
      Name: !Sub '${AWS::StackName}-AZs'
  AZA:
    Description: AZ of A
    Value: !Select 
      - 0
      - !GetAZs ''
    Export:
      Name: !Sub '${AWS::StackName}-AZA'
  AZB:
    Description: AZ of B
    Value: !Select 
      - 1
      - !GetAZs ''
    Export:
      Name: !Sub '${AWS::StackName}-AZB'
  CidrBlock:
    Description: The set of IP addresses for the VPC.
    Value: !GetAtt VPC.CidrBlock
    Export:
      Name: !Sub '${AWS::StackName}-CidrBlock'
  VPC:
    Description: VPC.
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VPC'
  SubnetsPublic:
    Description: Subnets public.
    Value: !Join 
      - ','
      - - !Ref SubnetAPublic
        - !Ref SubnetBPublic
    Export:
      Name: !Sub '${AWS::StackName}-SubnetsPublic'
  RouteTablesPublic:
    Description: Route tables public.
    Value: !Join 
      - ','
      - - !Ref RouteTablePublic
        - !Ref RouteTableBPublic
    Export:
      Name: !Sub '${AWS::StackName}-RouteTablesPublic'
  SubnetAPublic:
    Description: Subnet A public.
    Value: !Ref SubnetAPublic
    Export:
      Name: !Sub '${AWS::StackName}-SubnetAPublic'
  RouteTableAPublic:
    Description: Route table A public.
    Value: !Ref RouteTablePublic
    Export:
      Name: !Sub '${AWS::StackName}-RouteTableAPublic'
  SubnetBPublic:
    Description: Subnet B public.
    Value: !Ref SubnetBPublic
    Export:
      Name: !Sub '${AWS::StackName}-SubnetBPublic'
  RouteTableBPublic:
    Description: Route table B public.
    Value: !Ref RouteTableBPublic
    Export:
      Name: !Sub '${AWS::StackName}-RouteTableBPublic'
